# Generated by Django 5.1 on 2024-09-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 19, 15, 54, 176805, tzinfo=datetime.timezone.utc)),
        ),
    ]
